# Number of replicas for the Deployment
replicas: 1

# Triton server ports
grpcPort:   8001
httpPort:   8000

# Name of the image pull secret
imagePullSecret: regcred

# Full path (url) to the image and the tag to use
imageName:
imageTag: latest

# Hostname for the ingress
hostname:

# Credentials for creating an image pull secret
imageCredentials:
  registry:
  username:
  password:
  email:

tolerations: []
## If you want to set tolerations, delete the `[]` in the line above
## and uncomment/fill in this example block
# - key: "octoml.ai/octomizer-platform"
#   operator: "Equal"
#   value: "aws-c6g.large"
#   effect: "NoSchedule"

nodeSelector: {}
## If you want to set node selector, delete the `{}` in the line above
## and uncomment/fill in this example block
#  octoml.ai/octomizer-platform: "aws-c6g.large"
#  label-key: "label-value"
